OrdererOrgs:
  - Name: Orderer 
    Domain: orderer.com
    EnableNodeOUs: true
    Specs: 
      - Hostname: orderer0
      - Hostname: orderer1
      - Hostname: orderer2
PeerOrgs:
  - Name: EveryCRED
    Domain: org.everycred.com
    EnableNodeOUs: true
    Template: 
      Count: 3
    Users:
      Count: 3 

